# Generated by Django 5.0.3 on 2024-03-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicaredata',
            table='medicare_data',
        ),
    ]
