# Generated by Django 5.0.3 on 2024-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_alter_medicaredata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaredata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
