# Generated by Django 5.0.3 on 2024-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_alter_medicaredata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaredata',
            name='tot_bene_day_srvcs',
            field=models.FloatField(),
        ),
    ]
