# Generated by Django 5.0.3 on 2024-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_alter_medicaredata_tot_bene_day_srvcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaredata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
