# Generated by Django 5.0.3 on 2024-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaredata',
            name='serial_no',
            field=models.CharField(max_length=255),
        ),
    ]
