# Generated by Django 5.0.3 on 2024-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0008_alter_medicaredata_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaredata',
            name='tot_benes',
            field=models.CharField(max_length=255),
        ),
    ]
