# Generated by Django 5.0.3 on 2024-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0012_alter_medicaredata_tot_srvcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaredata',
            name='rndrng_prvdr_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
